run:
  build-tags:
  - e2e
  skip-dirs:
  - vendor
  - pkg/client/clientset/(.*)/fake
  - pkg/client/injection
  skip-files:
  - .*/zz_generated.deepcopy.go
  - pkg/apis/triggers/v1beta1/openapi_generated.go
linters-settings:
  errcheck:
    exclude: .errcheck.txt
linters:
  enable:
  - bodyclose
  - containedctx
  - decorder
  - depguard
  - dogsled
  - dupword
  - errcheck
  - errchkjson
  - errname
  - errorlint
  - exhaustive
  - goconst
  - gocritic
  - gofmt
  - goimports
  - gomodguard
  - gosec
  - gosimple
  - govet
  - maintidx
  - makezero
  - misspell
  - musttag
  - nakedret
  - nilerr
  - nilnil
  - noctx
  - nolintlint
  - nosprintfhostport
  - thelper
  - typecheck
  - unconvert
  - unused
  - usestdlibvars
  - whitespace
  disable:
  - cyclop
  - dupl
  - exhaustruct
  - forcetypeassert
  - funlen
  - gci
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - gocyclo
  - godot
  - godox
  - err113
  - gofumpt
  - gomoddirectives
  - iface
  - ireturn
  - lll
  - mnd
  - nestif
  - nlreturn
  - nonamedreturns
  - paralleltest
  - prealloc
  - predeclared
  - recvcheck
  - revive
  - staticcheck
  - stylecheck
  - tagliatelle
  - testpackage
  - tparallel
  - unparam
  - varnamelen
  - wastedassign
  - wrapcheck
  - wsl
  # Enabling presets means that new linters that we automatically adopt new
  # linters that augment a preset. This also opts us in for replacement linters
  # when a linter is deprecated.
  presets:
  - bugs
  - comment
  - complexity
  - error
  - format
  - import
  - metalinter
  - module
  - performance
  - sql
  - style
  - test
  - unused
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
  max-issues-per-linter: 0
  max-same-issues: 0
  # TODO(abayer): Enable off-by-default rules for revive requiring that all exported elements have a properly formatted comment, like we do in Pipeline.
  modules-download-mode: vendor
  timeout: 20m
